package com.piotrmarkowski.pmemories.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.piotrmarkowski.pmemories.R
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.tasks.await
import java.security.MessageDigest
import java.util.UUID

/**
 * Google Sign-In (Firebase Auth) — Android analog of iOS `AuthManager`
 * (Sign in with Apple). Same identification purpose: the only way the app
 * knows WHOSE score to write to the leaderboard — no local user account
 * otherwise exists (everything else is local Room data on-device).
 *
 * Uses Credential Manager (`androidx.credentials`), not the older,
 * deprecated `GoogleSignInClient`/`GoogleSignInApi` — same "always the
 * current, recommended API" stance as the rest of this project.
 *
 * `default_web_client_id` is a String resource auto-generated by the
 * `google-services` Gradle plugin FROM `google-services.json` (the
 * project's "Web application" OAuth client, `client_type: 3`) — nothing to
 * hardcode here, it updates automatically once the real config file
 * replaces the placeholder (see `Android.md` Etap 4).
 */
object AuthManager {
    private val auth = FirebaseAuth.getInstance()

    private val _isSignedIn = MutableStateFlow(auth.currentUser != null)
    val isSignedIn: StateFlow<Boolean> = _isSignedIn.asStateFlow()

    private val _displayName = MutableStateFlow(firstWordOf(auth.currentUser?.displayName))
    val displayName: StateFlow<String?> = _displayName.asStateFlow()

    val userIdentifier: String? get() = auth.currentUser?.uid

    suspend fun signIn(context: Context): Result<Unit> {
        return try {
            // Nonce zapobiega replay-atakom na token Google — standardowa
            // praktyka, wymagana przez Firebase dla logowania Google przez
            // Credential Manager.
            val nonce = UUID.randomUUID().toString()
            val hashedNonce = MessageDigest.getInstance("SHA-256")
                .digest(nonce.toByteArray())
                .joinToString("") { "%02x".format(it) }

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(context.getString(R.string.default_web_client_id))
                .setNonce(hashedNonce)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val credentialManager = CredentialManager.create(context)
            val result = credentialManager.getCredential(context, request)

            val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(result.credential.data)
            val firebaseCredential = GoogleAuthProvider.getCredential(googleIdTokenCredential.idToken, null)
            val authResult = auth.signInWithCredential(firebaseCredential).await()

            // Ten sam fix co iOS AuthManager (09.08.2026, user: "dlaczego
            // pojawia się moje pełne imię i nazwisko?") — tylko pierwsze
            // słowo, od razu, zamiast powtarzać ten sam bug tutaj i łatać
            // go później.
            _displayName.value = firstWordOf(authResult.user?.displayName) ?: "Traveler"
            _isSignedIn.value = true
            Result.success(Unit)
        } catch (e: GetCredentialException) {
            Result.failure(e)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    fun signOut() {
        auth.signOut()
        _isSignedIn.value = false
        _displayName.value = null
    }

    private fun firstWordOf(name: String?): String? =
        name?.trim()?.split(" ")?.firstOrNull()?.takeIf { it.isNotEmpty() }
}
